"""
Test cases for Valid Anagram.

Each entry is a tuple: (s, t, expected)

Usage:
    from test_cases import TEST_CASES

    for s, t, expected in TEST_CASES:
        result = is_anagram(s, t)
        assert result == expected, f"Failed: {s}, {t}"
"""

TEST_CASES = [
    ('racecar', 'carrace', True),
    ('jar', 'jam', False),
    ('a', 'a', True),
    ('a', 'b', False),
    ('ab', 'a', False),
    ('abc', 'abcd', False),
    ('aacc', 'ccac', False),
    ('aabbcc', 'abcabc', True),
    ('listen', 'silent', True),
    ('hello', 'world', False),
    ('anagram', 'nagaram', True),
    ('rat', 'car', False),
    ('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', True),
    ('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', False),
    ('z', 'z', True),
    ('aa', 'aa', True),
    ('aa', 'ab', False),
    ('abcdefg', 'gfedcba', True),
    ('aaaa', 'aaab', False),
    ('thisisalongword', 'wordalongisisthi', False),
    ('ctgdctopacgpossklhwte', 'goppwdcchktelsttocags', True),
    ('hqxjebruzwwjlvejrs', 'wejvqhlrjzwerjsubx', True),
    ('bxosfmxqd', 'bxqdxfmso', True),
    ('pjzdmtwderpkpmgoyrcxttiheassz', 'zgpiepracmjodthpskmwxszrtdyte', True),
    ('bttdmogwlfosfizqlndfipffbqf', 'pbidoqbsffdfzfffimngqlwltot', True),
    ('qqbsucendemwbvwcqoactg', 'segcbdqmownuwqacqbetcv', True),
    ('ibmxnbnwbbwkyopbcroigrig', 'wboncrkgoxbybbiiimwpbgrn', True),
    ('lohzun', 'olzhun', True),
    ('ddcohpsfqgmxvclhauqgtolabwxov', 'lpbotdhwmaclvqvgofsoaxgdxchuq', True),
    ('esjbmfxjv', 'xjmjsfevb', True),
    ('bujnrviawgpzapiulzdxeblnuryt', 'abazueiunuwrytvrdlgnlxpbjpzi', True),
    ('hlprmlfmxu', 'xrhuflmmlp', True),
    ('iudbzptlxosjkdrxwxufus', 'iudftwxdpojxsukzsblxur', True),
    ('ewltvhumglsgixcdjdfkimbvkuyaw', 'ktvbsvwmlkhcujugwymidxalgedif', True),
    ('qdm', 'mdq', True),
    ('iliwhykvmtbyf', 'viyfhtkmwyibl', True),
    ('rofsteptcvzcairy', 'crfrteptyizvosca', True),
    ('nrbqakmljxld', 'knrdxmqllajb', True),
    ('yhltorimimjghpwonegkogmslah', 'jtwliyhksolhriaponeogggmmmh', True),
    ('fmsznhc', 'znfhcsm', True),
    ('s', 's', True),
    ('hzosd', 'ozdhs', True),
    ('mizgwcbmprdvycgo', 'cmivwzdmbpgoygrc', True),
    ('yctqgcgoekrmahhwbggu', 'bkheucwamycggtroqhgg', True),
    ('rsynmcbligczvoy', 'ocbnyszilyrgmcv', True),
    ('mki', 'kim', True),
    ('kmrktacgduw', 'uakrtmwcgdk', True),
    ('lbgdhwmaqusiakfvcyqey', 'whbyylsiafmgqadevkqcu', True),
    ('asvprwlmitjywzgjwkimxjzuqdz', 'qtyxwkilwmmsvujzzajdzgpjiwr', True),
    ('oqgrhfcztscehaibjlgkreepjrmp', 'arerqbhkecchgjpgflspoejmtriz', True),
    ('jjhsavka', 'kjahsvaj', True),
    ('qqrsrvqx', 'qrvqxsrq', True),
    ('xik', 'ikx', True),
    ('oznxvgvmuticzdzwszzujuanlr', 'angldrsvvnzzutziowmxcjzzuu', True),
    ('cxdl', 'xcdl', True),
    ('kcmkyajlywcrozjkedwlrqpaugdob', 'akkwejbarzrpcmogoqyklycldwjdu', True),
    ('btntmuncn', 'nntcnutmb', True),
    ('rmxbcpbhqoiznl', 'rcpxhilnbqzmbo', True),
    ('siigyrmccltjdb', 'yilsgcdjmitrbc', True),
    ('cnemwjochflo', 'omjcenlwchof', True),
    ('e', 'e', True),
    ('okdqa', 'odqka', True),
    ('ijsuocbeqrhrmlh', 'hruisrleohbcjqm', True),
    ('bfytthdmldnforjktllc', 'jdlkttfcmyhbdftlorln', True),
    ('cwtfubqnfujyqdcge', 'ecfwcfqbduynjqgtu', True),
    ('lhhbnilbvbwwpnmo', 'onnvlwlhmibwbpbh', True),
    ('qbsznpjxkurbqiiok', 'qbszkpjxkurbqiiok', False),
    ('pdj', 'skp', False),
    ('iju', 'crnaiyit', False),
    ('fdcvcuv', 'aitdjev', False),
    ('qxsbjszptuggzuxfroluunkef', 'dgqwocvwhthxdlyfljabngzja', False),
    ('csidaxmvtmpxafdyplugdgqqbvmnqo', 'dlpgkrczbnnzokmqzgauitqutibove', False),
    ('rzmedsyafuxiikvmaqhwbrhul', 'rzmedsyafuxiikvmaqhwbrhol', False),
    ('yierjugcllzehcihlsellsxplqubr', 'yierjugcllzqhcihlsellsxplqubr', False),
    ('teawrldgqjyadljlbdjihyaenx', 'usfpszfdbeszvzzrsohhessejfzug', False),
    ('aojuopcizsntvbzq', 'aojuopcizsntvbvq', False),
    ('iwuqezlxbddeisiyx', 'fyhqpcqppeqxiybwcyug', False),
    ('tkqmqhy', 'tzqmqhy', False),
    ('rhbblmfpistwzdjoimggchjpgw', 'yseezmwmcklgpbhpvrhacdgjkbboj', False),
    ('bnthzrdzku', 'bnthzrdzlu', False),
    ('dpkbbsundxdyikqvpnnmomaic', 'dpkbbsundxdyikqvpnjmomaic', False),
    ('xwqpgrzpfbmnsujvgoselkkfnp', 'xwqpgrzpfbmnsujvgoselkkxnp', False),
    ('sn', 'ir', False),
    ('jylnorwrugmyhhyzu', 'fsijyuhdrjzvyuhhs', False),
    ('yrtfvhohctgb', 'fgcimrdzzeqw', False),
    ('mfziqxconsyxewex', 'mfziqxconsyxewef', False),
    ('twhahpyilqnxdnhvitqsaihrfpqkli', 'twhahpyilqnxdnhvitqsadhrfpqkli', False),
    ('zmyajl', 'zmjajl', False),
    ('saqsbdhknxsidxhpfdd', 'zjsxtuvtrpunnjxcvxf', False),
    ('dindfpcnvlnlbmuskv', 'fblsobxzmhedqszjxl', False),
    ('xjrroqjennsfaahronvgjhyscvktwa', 'capsbtkgfwbnhvtiprihdrfhbywxqlm', False),
    ('yruikdjtmwhs', 'rruikdjtmwhs', False),
    ('zodgfqxwcsegrp', 'uprffxhxfetttxss', False),
    ('xoujnjgnmczmv', 'ibwtaopshffogoyi', False),
    ('vzqmeuesmxoqbawyrtkvgsanj', 'qyxrankasnhnslyexngqgjucy', False),
    ('ozfrwqwtcjobaem', 'ozfrwqwtcjzbaem', False),
    ('owcnbfwxmbb', 'owcnbfwxsbb', False),
    ('ayiyptskcegvkxitdzsnzb', 'ayiyptsccegvkxitdzsnzb', False),
    ('pppziqulfoj', 'rcquscesqticaijh', False),
    ('clonc', 'opuwakus', False),
]
